[package]
name = "ariel-os-runqueue"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
description = "Ariel OS runqueue implementation"

[dependencies]
# Put a symlink to creusot at the root of this repository
creusot-contracts = { path = "creusot/creusot-contracts" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(creusot)'] }
